#!/bin/bash
#
# Copyright (C) 2011 Yung-Yu Chen <yyc@solvcon.net>.

PYTHON=$YHROOT/opt/bin/python3

# build.
showrealpath () {
 echo "$(cd "$(dirname $1)" && pwd)/$1"
}

echo "start building:"
{ time $PYTHON setup.py build -j $NP ; } > build.log 2>&1
echo "building done: $(showrealpath build.log)"

echo "start installation:"
{ time $PYTHON setup.py install --old-and-unmanageable ; } > install.log 2>&1
echo "installation done: $(showrealpath install.log)"

# vim: set et nobomb ff=unix fenc=utf8:
